### ISSUE TITLE
Update to Pi-hole Docker Tag 2022.08 and FTL v5.16.1 

### ISSUE THREAD

**Issue by corasaniti** [chriscrowe/docker-pihole-unbound#148]
please when You update to Pi-hole Docker Tag 2022.08 and FTL v5.16.1 
Thanks in advance
PC

**Comment by DKeppi** [comment]
I think this time, its not so easy at all.

Setting VERSION to 2022.08 is not enough, because they changed s6 overlay to v3 - tried it already and it doesnt work!
Error in Container-Log: S6-Supervise (child): S6 Fatal: Unable to spawn ./run: No such file or directory

I think we will need a few new unbound files in the container directory /etc/s6-overlay/s6-rc.d/ to work -> run, type, finish, dependencies

But chriscrowe would know better than me ;)

**Comment by DKeppi** [comment]
New Release:

Latest Docker Image has now PIHOLE_DOCKER_TAG=2022.08.1

**Comment by corasaniti** [comment]
@DKeppi 
no the latest Docker Tag is 2022.08 instead of 2022.08.1

**Comment by DKeppi** [comment]
https://hub.docker.com/layers/pihole/pihole/pihole/2022.08.1/images/sha256-df3461634dc517294305920eb95355b51a64407c6b051e27a1aae7817e8c3124?context=explore

**Comment by DKeppi** [comment]
And since this morning its Docker Tag 2022.08.2 ;)

**Comment by chriscrowe** [comment]
2022.08.2 released -- their upstream container was a bugfix for an s6 regression when using Podman. Now y'all know why I don't rush to make new releases when the upstream is updated 😜

**Comment by DKeppi** [comment]
Thx, it works :)

**Comment by corasaniti** [comment]
@chriscrowe thanks :-)
