### ISSUE TITLE
Change ports

### ISSUE THREAD

**Issue by Rar9** [chriscrowe/docker-pihole-unbound#35]
In my yml i defined a different port for one container. 

      - 90:80/tcp 
      
But its being ignored

**Comment by chriscrowe** [comment]
This is because we're using [host networking](https://docs.docker.com/network/host/) in the Docker config. In fact the port definitions that are there are in my docker-compose file are currently being entirely ignored (removing them and testing for regressions has been on my todo list).

If you need to remap ports I recommend changing to the default [bridge networking](https://docs.docker.com/network/bridge/) -- I actually think I'll be changing the default behavior in this repo to do that soon.

**Comment by Rar9** [comment]
Thanks for the quick feedback

So best to use the 2 separate unbound /pihole container images for the time being?

**Comment by chriscrowe** [comment]
Not necessary-- you could adapt the docker-compose file to use bridge networks. I'm actually playing with this now, stand by.

**Comment by Rar9** [comment]
I'm using portainer only

I`s like to use port 80 for nginx proxy manager ... thats why I also asked if pihole can run without lighttd and use nginx as webserver.

**Comment by chriscrowe** [comment]
Made a new release with bridge networking so now you can use port mappings:

https://github.com/chriscrowe/docker-pihole-unbound/releases/tag/v5.7-bridge

Note that there are some new config changes you might need to deal with -- please read the release notes.

**Comment by Rar9** [comment]
i have fully remove the onecontainer from portainer.
install NPM and then onecontainer via docker-compose.yml and added .env

I get now get 
ERROR: for pihole-unbound  Cannot start service pihole: driver failed programming external connectivity on endpoint pihole-unbound (xxx): Bind for 0.0.0.0:443 failed: port is already allocated

**Comment by chriscrowe** [comment]
Pull in my latest docker-compose.yaml file-- I made some changes.

**Comment by Rar9** [comment]
Thanks all working--- now its tweaking time

**Comment by Rar9** [comment]
When u find the time please add 

HOSTNAME=pihole
DOMAIN_NAME=pihole.local

to your .env guide

Where is the Unbound.conf located?
